name: kanz website deployment

on:
  push:
    branches: [ master ]
env:
  REGISTRY: gchr.io
  image: ${{ github.repository }}

jobs:

  test:
   strategy:
      matrix:
        node-version: ["24.15.0"]
        os: [ubuntu-latest]
   runs-on: ${{ matrix.os }}
   steps:

        - name: Clone repository
          uses: actions/checkout@v6

        - name: Install Node.js ${{matrix.node-version}}
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          working-directory: ./
          run: npm install

  build-and-push-dockerhub:

    needs: test
    strategy:
      matrix:
        node-version: ["24.15.0"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:

        - name: Clone repository
          uses: actions/checkout@v6

        - name: Docker login
          run:
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

        - name: Build and push Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/kanzfrontend .
            docker push ${{ secrets.DOCKER_USERNAME }}/kanzfrontend

  deploy-project-toEc2:
    needs: build-and-push-dockerhub
    strategy:
      matrix:
        node-version: ["24.15.0"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:

        - name: ec2 deploy
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            

        - name: Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USER }}
            key: ${{ secrets.EC2_SSH_KEY }}
            port: 22
            script: |
              if [ ! -d "Kanz_with_docker/.git" ]; then
              git clone https://github.com/sufiye/Kanz_with_docker.git
              fi

              cd Kanz_with_docker
              git pull origin master
              docker compose pull
              docker compose down
              docker compose up -d
              docker image prune -f
  
